# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='No image', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='notesfiles',
            field=models.FileField(default='no pdf', null=True, upload_to=''),
        ),
    ]
