# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20201011_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.ImageField(upload_to='images'),
        ),
    ]
