# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-11 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(default='SOME STRING', upload_to='video/%y'),
        ),
    ]
