# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-11 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20201011_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
