# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-14 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20210514_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
