# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20210514_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Comments'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trash'), (2, 'Horrible'), (3, 'Terrible'), (4, 'Bad'), (5, 'OK'), (6, 'Readable'), (7, 'Good'), (8, 'Very Good'), (9, 'Perfect'), (10, 'Master Piece')]),
        ),
    ]
