# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-15 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20210515_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sno',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
